services:
  app:
    image: ranckosolutionsinc/budget-tracker:latest
    ports:
      - 5354:3000
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/wizard	
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/wizard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_OUT_URL=/sign-in
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net
    external: true

